# Generated by Django 4.2.2 on 2023-07-17 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_permission_user_is_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
    ]
